//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AgenciesI18n = newAgenciesI18nTable("public", "agencies_i18n", "")

type agenciesI18nTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	LanguageCode postgres.ColumnString
	AgencyID     postgres.ColumnInteger
	Name         postgres.ColumnString
	Description  postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AgenciesI18nTable struct {
	agenciesI18nTable

	EXCLUDED agenciesI18nTable
}

// AS creates new AgenciesI18nTable with assigned alias
func (a AgenciesI18nTable) AS(alias string) *AgenciesI18nTable {
	return newAgenciesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AgenciesI18nTable with assigned schema name
func (a AgenciesI18nTable) FromSchema(schemaName string) *AgenciesI18nTable {
	return newAgenciesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AgenciesI18nTable with assigned table prefix
func (a AgenciesI18nTable) WithPrefix(prefix string) *AgenciesI18nTable {
	return newAgenciesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AgenciesI18nTable with assigned table suffix
func (a AgenciesI18nTable) WithSuffix(suffix string) *AgenciesI18nTable {
	return newAgenciesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAgenciesI18nTable(schemaName, tableName, alias string) *AgenciesI18nTable {
	return &AgenciesI18nTable{
		agenciesI18nTable: newAgenciesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newAgenciesI18nTableImpl("", "excluded", ""),
	}
}

func newAgenciesI18nTableImpl(schemaName, tableName, alias string) agenciesI18nTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		LanguageCodeColumn = postgres.StringColumn("language_code")
		AgencyIDColumn     = postgres.IntegerColumn("agency_id")
		NameColumn         = postgres.StringColumn("name")
		DescriptionColumn  = postgres.StringColumn("description")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, LanguageCodeColumn, AgencyIDColumn, NameColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{LanguageCodeColumn, AgencyIDColumn, NameColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return agenciesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		LanguageCode: LanguageCodeColumn,
		AgencyID:     AgencyIDColumn,
		Name:         NameColumn,
		Description:  DescriptionColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
