//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AgencyReviews = newAgencyReviewsTable("public", "agency_reviews", "")

type agencyReviewsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	AgencyID   postgres.ColumnInteger
	CustomerID postgres.ColumnInteger
	Content    postgres.ColumnString
	Rating     postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AgencyReviewsTable struct {
	agencyReviewsTable

	EXCLUDED agencyReviewsTable
}

// AS creates new AgencyReviewsTable with assigned alias
func (a AgencyReviewsTable) AS(alias string) *AgencyReviewsTable {
	return newAgencyReviewsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AgencyReviewsTable with assigned schema name
func (a AgencyReviewsTable) FromSchema(schemaName string) *AgencyReviewsTable {
	return newAgencyReviewsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AgencyReviewsTable with assigned table prefix
func (a AgencyReviewsTable) WithPrefix(prefix string) *AgencyReviewsTable {
	return newAgencyReviewsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AgencyReviewsTable with assigned table suffix
func (a AgencyReviewsTable) WithSuffix(suffix string) *AgencyReviewsTable {
	return newAgencyReviewsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAgencyReviewsTable(schemaName, tableName, alias string) *AgencyReviewsTable {
	return &AgencyReviewsTable{
		agencyReviewsTable: newAgencyReviewsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAgencyReviewsTableImpl("", "excluded", ""),
	}
}

func newAgencyReviewsTableImpl(schemaName, tableName, alias string) agencyReviewsTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		AgencyIDColumn   = postgres.IntegerColumn("agency_id")
		CustomerIDColumn = postgres.IntegerColumn("customer_id")
		ContentColumn    = postgres.StringColumn("content")
		RatingColumn     = postgres.IntegerColumn("rating")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, AgencyIDColumn, CustomerIDColumn, ContentColumn, RatingColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{AgencyIDColumn, CustomerIDColumn, ContentColumn, RatingColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return agencyReviewsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		AgencyID:   AgencyIDColumn,
		CustomerID: CustomerIDColumn,
		Content:    ContentColumn,
		Rating:     RatingColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
