//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AgencyPhoneNumbers = newAgencyPhoneNumbersTable("public", "agency_phone_numbers", "")

type agencyPhoneNumbersTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	AgencyID    postgres.ColumnInteger
	CountryCode postgres.ColumnString
	PhoneNumber postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AgencyPhoneNumbersTable struct {
	agencyPhoneNumbersTable

	EXCLUDED agencyPhoneNumbersTable
}

// AS creates new AgencyPhoneNumbersTable with assigned alias
func (a AgencyPhoneNumbersTable) AS(alias string) *AgencyPhoneNumbersTable {
	return newAgencyPhoneNumbersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AgencyPhoneNumbersTable with assigned schema name
func (a AgencyPhoneNumbersTable) FromSchema(schemaName string) *AgencyPhoneNumbersTable {
	return newAgencyPhoneNumbersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AgencyPhoneNumbersTable with assigned table prefix
func (a AgencyPhoneNumbersTable) WithPrefix(prefix string) *AgencyPhoneNumbersTable {
	return newAgencyPhoneNumbersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AgencyPhoneNumbersTable with assigned table suffix
func (a AgencyPhoneNumbersTable) WithSuffix(suffix string) *AgencyPhoneNumbersTable {
	return newAgencyPhoneNumbersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAgencyPhoneNumbersTable(schemaName, tableName, alias string) *AgencyPhoneNumbersTable {
	return &AgencyPhoneNumbersTable{
		agencyPhoneNumbersTable: newAgencyPhoneNumbersTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newAgencyPhoneNumbersTableImpl("", "excluded", ""),
	}
}

func newAgencyPhoneNumbersTableImpl(schemaName, tableName, alias string) agencyPhoneNumbersTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		AgencyIDColumn    = postgres.IntegerColumn("agency_id")
		CountryCodeColumn = postgres.StringColumn("country_code")
		PhoneNumberColumn = postgres.StringColumn("phone_number")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, AgencyIDColumn, CountryCodeColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{AgencyIDColumn, CountryCodeColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return agencyPhoneNumbersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		AgencyID:    AgencyIDColumn,
		CountryCode: CountryCodeColumn,
		PhoneNumber: PhoneNumberColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
