//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AgencyAgents = newAgencyAgentsTable("public", "agency_agents", "")

type agencyAgentsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	UserID    postgres.ColumnInteger
	AgencyID  postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AgencyAgentsTable struct {
	agencyAgentsTable

	EXCLUDED agencyAgentsTable
}

// AS creates new AgencyAgentsTable with assigned alias
func (a AgencyAgentsTable) AS(alias string) *AgencyAgentsTable {
	return newAgencyAgentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AgencyAgentsTable with assigned schema name
func (a AgencyAgentsTable) FromSchema(schemaName string) *AgencyAgentsTable {
	return newAgencyAgentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AgencyAgentsTable with assigned table prefix
func (a AgencyAgentsTable) WithPrefix(prefix string) *AgencyAgentsTable {
	return newAgencyAgentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AgencyAgentsTable with assigned table suffix
func (a AgencyAgentsTable) WithSuffix(suffix string) *AgencyAgentsTable {
	return newAgencyAgentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAgencyAgentsTable(schemaName, tableName, alias string) *AgencyAgentsTable {
	return &AgencyAgentsTable{
		agencyAgentsTable: newAgencyAgentsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newAgencyAgentsTableImpl("", "excluded", ""),
	}
}

func newAgencyAgentsTableImpl(schemaName, tableName, alias string) agencyAgentsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		UserIDColumn    = postgres.IntegerColumn("user_id")
		AgencyIDColumn  = postgres.IntegerColumn("agency_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, AgencyIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, AgencyIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return agencyAgentsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		AgencyID:  AgencyIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
