//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Agencies = newAgenciesTable("public", "agencies", "")

type agenciesTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	Slug         postgres.ColumnString
	EmailAddress postgres.ColumnString
	Logo         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AgenciesTable struct {
	agenciesTable

	EXCLUDED agenciesTable
}

// AS creates new AgenciesTable with assigned alias
func (a AgenciesTable) AS(alias string) *AgenciesTable {
	return newAgenciesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AgenciesTable with assigned schema name
func (a AgenciesTable) FromSchema(schemaName string) *AgenciesTable {
	return newAgenciesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AgenciesTable with assigned table prefix
func (a AgenciesTable) WithPrefix(prefix string) *AgenciesTable {
	return newAgenciesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AgenciesTable with assigned table suffix
func (a AgenciesTable) WithSuffix(suffix string) *AgenciesTable {
	return newAgenciesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAgenciesTable(schemaName, tableName, alias string) *AgenciesTable {
	return &AgenciesTable{
		agenciesTable: newAgenciesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newAgenciesTableImpl("", "excluded", ""),
	}
}

func newAgenciesTableImpl(schemaName, tableName, alias string) agenciesTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		SlugColumn         = postgres.StringColumn("slug")
		EmailAddressColumn = postgres.StringColumn("email_address")
		LogoColumn         = postgres.StringColumn("logo")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, SlugColumn, EmailAddressColumn, LogoColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{SlugColumn, EmailAddressColumn, LogoColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return agenciesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Slug:         SlugColumn,
		EmailAddress: EmailAddressColumn,
		Logo:         LogoColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
