//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AreasI18n = newAreasI18nTable("public", "areas_i18n", "")

type areasI18nTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	LanguageCode postgres.ColumnString
	AreaID       postgres.ColumnInteger
	Name         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AreasI18nTable struct {
	areasI18nTable

	EXCLUDED areasI18nTable
}

// AS creates new AreasI18nTable with assigned alias
func (a AreasI18nTable) AS(alias string) *AreasI18nTable {
	return newAreasI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AreasI18nTable with assigned schema name
func (a AreasI18nTable) FromSchema(schemaName string) *AreasI18nTable {
	return newAreasI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AreasI18nTable with assigned table prefix
func (a AreasI18nTable) WithPrefix(prefix string) *AreasI18nTable {
	return newAreasI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AreasI18nTable with assigned table suffix
func (a AreasI18nTable) WithSuffix(suffix string) *AreasI18nTable {
	return newAreasI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAreasI18nTable(schemaName, tableName, alias string) *AreasI18nTable {
	return &AreasI18nTable{
		areasI18nTable: newAreasI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newAreasI18nTableImpl("", "excluded", ""),
	}
}

func newAreasI18nTableImpl(schemaName, tableName, alias string) areasI18nTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		LanguageCodeColumn = postgres.StringColumn("language_code")
		AreaIDColumn       = postgres.IntegerColumn("area_id")
		NameColumn         = postgres.StringColumn("name")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, LanguageCodeColumn, AreaIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{LanguageCodeColumn, AreaIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return areasI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		LanguageCode: LanguageCodeColumn,
		AreaID:       AreaIDColumn,
		Name:         NameColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
