//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Areas = newAreasTable("public", "areas", "")

type areasTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	CityID    postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AreasTable struct {
	areasTable

	EXCLUDED areasTable
}

// AS creates new AreasTable with assigned alias
func (a AreasTable) AS(alias string) *AreasTable {
	return newAreasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AreasTable with assigned schema name
func (a AreasTable) FromSchema(schemaName string) *AreasTable {
	return newAreasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AreasTable with assigned table prefix
func (a AreasTable) WithPrefix(prefix string) *AreasTable {
	return newAreasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AreasTable with assigned table suffix
func (a AreasTable) WithSuffix(suffix string) *AreasTable {
	return newAreasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAreasTable(schemaName, tableName, alias string) *AreasTable {
	return &AreasTable{
		areasTable: newAreasTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newAreasTableImpl("", "excluded", ""),
	}
}

func newAreasTableImpl(schemaName, tableName, alias string) areasTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CityIDColumn    = postgres.IntegerColumn("city_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, CityIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CityIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return areasTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CityID:    CityIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
