//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Availabilities = newAvailabilitiesTable("public", "availabilities", "")

type availabilitiesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Code      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AvailabilitiesTable struct {
	availabilitiesTable

	EXCLUDED availabilitiesTable
}

// AS creates new AvailabilitiesTable with assigned alias
func (a AvailabilitiesTable) AS(alias string) *AvailabilitiesTable {
	return newAvailabilitiesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AvailabilitiesTable with assigned schema name
func (a AvailabilitiesTable) FromSchema(schemaName string) *AvailabilitiesTable {
	return newAvailabilitiesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AvailabilitiesTable with assigned table prefix
func (a AvailabilitiesTable) WithPrefix(prefix string) *AvailabilitiesTable {
	return newAvailabilitiesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AvailabilitiesTable with assigned table suffix
func (a AvailabilitiesTable) WithSuffix(suffix string) *AvailabilitiesTable {
	return newAvailabilitiesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAvailabilitiesTable(schemaName, tableName, alias string) *AvailabilitiesTable {
	return &AvailabilitiesTable{
		availabilitiesTable: newAvailabilitiesTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newAvailabilitiesTableImpl("", "excluded", ""),
	}
}

func newAvailabilitiesTableImpl(schemaName, tableName, alias string) availabilitiesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CodeColumn      = postgres.StringColumn("code")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CodeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return availabilitiesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Code:      CodeColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
