//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CitiesI18n = newCitiesI18nTable("public", "cities_i18n", "")

type citiesI18nTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	LanguageCode postgres.ColumnString
	CityID       postgres.ColumnInteger
	Name         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CitiesI18nTable struct {
	citiesI18nTable

	EXCLUDED citiesI18nTable
}

// AS creates new CitiesI18nTable with assigned alias
func (a CitiesI18nTable) AS(alias string) *CitiesI18nTable {
	return newCitiesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CitiesI18nTable with assigned schema name
func (a CitiesI18nTable) FromSchema(schemaName string) *CitiesI18nTable {
	return newCitiesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CitiesI18nTable with assigned table prefix
func (a CitiesI18nTable) WithPrefix(prefix string) *CitiesI18nTable {
	return newCitiesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CitiesI18nTable with assigned table suffix
func (a CitiesI18nTable) WithSuffix(suffix string) *CitiesI18nTable {
	return newCitiesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCitiesI18nTable(schemaName, tableName, alias string) *CitiesI18nTable {
	return &CitiesI18nTable{
		citiesI18nTable: newCitiesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newCitiesI18nTableImpl("", "excluded", ""),
	}
}

func newCitiesI18nTableImpl(schemaName, tableName, alias string) citiesI18nTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		LanguageCodeColumn = postgres.StringColumn("language_code")
		CityIDColumn       = postgres.IntegerColumn("city_id")
		NameColumn         = postgres.StringColumn("name")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, LanguageCodeColumn, CityIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{LanguageCodeColumn, CityIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return citiesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		LanguageCode: LanguageCodeColumn,
		CityID:       CityIDColumn,
		Name:         NameColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
