//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ConversationMessages = newConversationMessagesTable("public", "conversation_messages", "")

type conversationMessagesTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	ConversationID postgres.ColumnInteger
	Type           postgres.ColumnString
	Sender         postgres.ColumnString
	TextContent    postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ConversationMessagesTable struct {
	conversationMessagesTable

	EXCLUDED conversationMessagesTable
}

// AS creates new ConversationMessagesTable with assigned alias
func (a ConversationMessagesTable) AS(alias string) *ConversationMessagesTable {
	return newConversationMessagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ConversationMessagesTable with assigned schema name
func (a ConversationMessagesTable) FromSchema(schemaName string) *ConversationMessagesTable {
	return newConversationMessagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ConversationMessagesTable with assigned table prefix
func (a ConversationMessagesTable) WithPrefix(prefix string) *ConversationMessagesTable {
	return newConversationMessagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ConversationMessagesTable with assigned table suffix
func (a ConversationMessagesTable) WithSuffix(suffix string) *ConversationMessagesTable {
	return newConversationMessagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newConversationMessagesTable(schemaName, tableName, alias string) *ConversationMessagesTable {
	return &ConversationMessagesTable{
		conversationMessagesTable: newConversationMessagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newConversationMessagesTableImpl("", "excluded", ""),
	}
}

func newConversationMessagesTableImpl(schemaName, tableName, alias string) conversationMessagesTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		ConversationIDColumn = postgres.IntegerColumn("conversation_id")
		TypeColumn           = postgres.StringColumn("type")
		SenderColumn         = postgres.StringColumn("sender")
		TextContentColumn    = postgres.StringColumn("text_content")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{IDColumn, ConversationIDColumn, TypeColumn, SenderColumn, TextContentColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{ConversationIDColumn, TypeColumn, SenderColumn, TextContentColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return conversationMessagesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ConversationID: ConversationIDColumn,
		Type:           TypeColumn,
		Sender:         SenderColumn,
		TextContent:    TextContentColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
