//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Countries = newCountriesTable("public", "countries", "")

type countriesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Code      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CountriesTable struct {
	countriesTable

	EXCLUDED countriesTable
}

// AS creates new CountriesTable with assigned alias
func (a CountriesTable) AS(alias string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CountriesTable with assigned schema name
func (a CountriesTable) FromSchema(schemaName string) *CountriesTable {
	return newCountriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CountriesTable with assigned table prefix
func (a CountriesTable) WithPrefix(prefix string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CountriesTable with assigned table suffix
func (a CountriesTable) WithSuffix(suffix string) *CountriesTable {
	return newCountriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCountriesTable(schemaName, tableName, alias string) *CountriesTable {
	return &CountriesTable{
		countriesTable: newCountriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newCountriesTableImpl("", "excluded", ""),
	}
}

func newCountriesTableImpl(schemaName, tableName, alias string) countriesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CodeColumn      = postgres.StringColumn("code")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CodeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return countriesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Code:      CodeColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
