//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CountriesI18n = newCountriesI18nTable("public", "countries_i18n", "")

type countriesI18nTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	LanguageCode postgres.ColumnString
	CountryID    postgres.ColumnInteger
	Name         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CountriesI18nTable struct {
	countriesI18nTable

	EXCLUDED countriesI18nTable
}

// AS creates new CountriesI18nTable with assigned alias
func (a CountriesI18nTable) AS(alias string) *CountriesI18nTable {
	return newCountriesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CountriesI18nTable with assigned schema name
func (a CountriesI18nTable) FromSchema(schemaName string) *CountriesI18nTable {
	return newCountriesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CountriesI18nTable with assigned table prefix
func (a CountriesI18nTable) WithPrefix(prefix string) *CountriesI18nTable {
	return newCountriesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CountriesI18nTable with assigned table suffix
func (a CountriesI18nTable) WithSuffix(suffix string) *CountriesI18nTable {
	return newCountriesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCountriesI18nTable(schemaName, tableName, alias string) *CountriesI18nTable {
	return &CountriesI18nTable{
		countriesI18nTable: newCountriesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newCountriesI18nTableImpl("", "excluded", ""),
	}
}

func newCountriesI18nTableImpl(schemaName, tableName, alias string) countriesI18nTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		LanguageCodeColumn = postgres.StringColumn("language_code")
		CountryIDColumn    = postgres.IntegerColumn("country_id")
		NameColumn         = postgres.StringColumn("name")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, LanguageCodeColumn, CountryIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{LanguageCodeColumn, CountryIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return countriesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		LanguageCode: LanguageCodeColumn,
		CountryID:    CountryIDColumn,
		Name:         NameColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
