//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CustomerFavoriteListings = newCustomerFavoriteListingsTable("public", "customer_favorite_listings", "")

type customerFavoriteListingsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	CustomerID postgres.ColumnInteger
	ListingID  postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CustomerFavoriteListingsTable struct {
	customerFavoriteListingsTable

	EXCLUDED customerFavoriteListingsTable
}

// AS creates new CustomerFavoriteListingsTable with assigned alias
func (a CustomerFavoriteListingsTable) AS(alias string) *CustomerFavoriteListingsTable {
	return newCustomerFavoriteListingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CustomerFavoriteListingsTable with assigned schema name
func (a CustomerFavoriteListingsTable) FromSchema(schemaName string) *CustomerFavoriteListingsTable {
	return newCustomerFavoriteListingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CustomerFavoriteListingsTable with assigned table prefix
func (a CustomerFavoriteListingsTable) WithPrefix(prefix string) *CustomerFavoriteListingsTable {
	return newCustomerFavoriteListingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CustomerFavoriteListingsTable with assigned table suffix
func (a CustomerFavoriteListingsTable) WithSuffix(suffix string) *CustomerFavoriteListingsTable {
	return newCustomerFavoriteListingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCustomerFavoriteListingsTable(schemaName, tableName, alias string) *CustomerFavoriteListingsTable {
	return &CustomerFavoriteListingsTable{
		customerFavoriteListingsTable: newCustomerFavoriteListingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newCustomerFavoriteListingsTableImpl("", "excluded", ""),
	}
}

func newCustomerFavoriteListingsTableImpl(schemaName, tableName, alias string) customerFavoriteListingsTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		CustomerIDColumn = postgres.IntegerColumn("customer_id")
		ListingIDColumn  = postgres.IntegerColumn("listing_id")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, CustomerIDColumn, ListingIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{CustomerIDColumn, ListingIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return customerFavoriteListingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		CustomerID: CustomerIDColumn,
		ListingID:  ListingIDColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
