//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CustomerFollowedAgencies = newCustomerFollowedAgenciesTable("public", "customer_followed_agencies", "")

type customerFollowedAgenciesTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	CustomerID postgres.ColumnInteger
	AgencyID   postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CustomerFollowedAgenciesTable struct {
	customerFollowedAgenciesTable

	EXCLUDED customerFollowedAgenciesTable
}

// AS creates new CustomerFollowedAgenciesTable with assigned alias
func (a CustomerFollowedAgenciesTable) AS(alias string) *CustomerFollowedAgenciesTable {
	return newCustomerFollowedAgenciesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CustomerFollowedAgenciesTable with assigned schema name
func (a CustomerFollowedAgenciesTable) FromSchema(schemaName string) *CustomerFollowedAgenciesTable {
	return newCustomerFollowedAgenciesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CustomerFollowedAgenciesTable with assigned table prefix
func (a CustomerFollowedAgenciesTable) WithPrefix(prefix string) *CustomerFollowedAgenciesTable {
	return newCustomerFollowedAgenciesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CustomerFollowedAgenciesTable with assigned table suffix
func (a CustomerFollowedAgenciesTable) WithSuffix(suffix string) *CustomerFollowedAgenciesTable {
	return newCustomerFollowedAgenciesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCustomerFollowedAgenciesTable(schemaName, tableName, alias string) *CustomerFollowedAgenciesTable {
	return &CustomerFollowedAgenciesTable{
		customerFollowedAgenciesTable: newCustomerFollowedAgenciesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newCustomerFollowedAgenciesTableImpl("", "excluded", ""),
	}
}

func newCustomerFollowedAgenciesTableImpl(schemaName, tableName, alias string) customerFollowedAgenciesTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		CustomerIDColumn = postgres.IntegerColumn("customer_id")
		AgencyIDColumn   = postgres.IntegerColumn("agency_id")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, CustomerIDColumn, AgencyIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{CustomerIDColumn, AgencyIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return customerFollowedAgenciesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		CustomerID: CustomerIDColumn,
		AgencyID:   AgencyIDColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
