//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingTypes = newListingTypesTable("public", "listing_types", "")

type listingTypesTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	ParentTypeID postgres.ColumnInteger
	Code         postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingTypesTable struct {
	listingTypesTable

	EXCLUDED listingTypesTable
}

// AS creates new ListingTypesTable with assigned alias
func (a ListingTypesTable) AS(alias string) *ListingTypesTable {
	return newListingTypesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingTypesTable with assigned schema name
func (a ListingTypesTable) FromSchema(schemaName string) *ListingTypesTable {
	return newListingTypesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingTypesTable with assigned table prefix
func (a ListingTypesTable) WithPrefix(prefix string) *ListingTypesTable {
	return newListingTypesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingTypesTable with assigned table suffix
func (a ListingTypesTable) WithSuffix(suffix string) *ListingTypesTable {
	return newListingTypesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingTypesTable(schemaName, tableName, alias string) *ListingTypesTable {
	return &ListingTypesTable{
		listingTypesTable: newListingTypesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newListingTypesTableImpl("", "excluded", ""),
	}
}

func newListingTypesTableImpl(schemaName, tableName, alias string) listingTypesTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		ParentTypeIDColumn = postgres.IntegerColumn("parent_type_id")
		CodeColumn         = postgres.StringColumn("code")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, ParentTypeIDColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{ParentTypeIDColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingTypesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		ParentTypeID: ParentTypeIDColumn,
		Code:         CodeColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
