//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingExtraFeaturesI18n = newListingExtraFeaturesI18nTable("public", "listing_extra_features_i18n", "")

type listingExtraFeaturesI18nTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnInteger
	ListingExtraFeaturesID postgres.ColumnInteger
	LanguageCode           postgres.ColumnString
	Title                  postgres.ColumnString
	CreatedAt              postgres.ColumnTimestamp
	UpdatedAt              postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingExtraFeaturesI18nTable struct {
	listingExtraFeaturesI18nTable

	EXCLUDED listingExtraFeaturesI18nTable
}

// AS creates new ListingExtraFeaturesI18nTable with assigned alias
func (a ListingExtraFeaturesI18nTable) AS(alias string) *ListingExtraFeaturesI18nTable {
	return newListingExtraFeaturesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingExtraFeaturesI18nTable with assigned schema name
func (a ListingExtraFeaturesI18nTable) FromSchema(schemaName string) *ListingExtraFeaturesI18nTable {
	return newListingExtraFeaturesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingExtraFeaturesI18nTable with assigned table prefix
func (a ListingExtraFeaturesI18nTable) WithPrefix(prefix string) *ListingExtraFeaturesI18nTable {
	return newListingExtraFeaturesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingExtraFeaturesI18nTable with assigned table suffix
func (a ListingExtraFeaturesI18nTable) WithSuffix(suffix string) *ListingExtraFeaturesI18nTable {
	return newListingExtraFeaturesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingExtraFeaturesI18nTable(schemaName, tableName, alias string) *ListingExtraFeaturesI18nTable {
	return &ListingExtraFeaturesI18nTable{
		listingExtraFeaturesI18nTable: newListingExtraFeaturesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:                      newListingExtraFeaturesI18nTableImpl("", "excluded", ""),
	}
}

func newListingExtraFeaturesI18nTableImpl(schemaName, tableName, alias string) listingExtraFeaturesI18nTable {
	var (
		IDColumn                     = postgres.IntegerColumn("id")
		ListingExtraFeaturesIDColumn = postgres.IntegerColumn("listing_extra_features_id")
		LanguageCodeColumn           = postgres.StringColumn("language_code")
		TitleColumn                  = postgres.StringColumn("title")
		CreatedAtColumn              = postgres.TimestampColumn("created_at")
		UpdatedAtColumn              = postgres.TimestampColumn("updated_at")
		allColumns                   = postgres.ColumnList{IDColumn, ListingExtraFeaturesIDColumn, LanguageCodeColumn, TitleColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns               = postgres.ColumnList{ListingExtraFeaturesIDColumn, LanguageCodeColumn, TitleColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingExtraFeaturesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		ListingExtraFeaturesID: ListingExtraFeaturesIDColumn,
		LanguageCode:           LanguageCodeColumn,
		Title:                  TitleColumn,
		CreatedAt:              CreatedAtColumn,
		UpdatedAt:              UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
