//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingAvailabilities = newListingAvailabilitiesTable("public", "listing_availabilities", "")

type listingAvailabilitiesTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	AvailabilityID postgres.ColumnInteger
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp
	ListingID      postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingAvailabilitiesTable struct {
	listingAvailabilitiesTable

	EXCLUDED listingAvailabilitiesTable
}

// AS creates new ListingAvailabilitiesTable with assigned alias
func (a ListingAvailabilitiesTable) AS(alias string) *ListingAvailabilitiesTable {
	return newListingAvailabilitiesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingAvailabilitiesTable with assigned schema name
func (a ListingAvailabilitiesTable) FromSchema(schemaName string) *ListingAvailabilitiesTable {
	return newListingAvailabilitiesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingAvailabilitiesTable with assigned table prefix
func (a ListingAvailabilitiesTable) WithPrefix(prefix string) *ListingAvailabilitiesTable {
	return newListingAvailabilitiesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingAvailabilitiesTable with assigned table suffix
func (a ListingAvailabilitiesTable) WithSuffix(suffix string) *ListingAvailabilitiesTable {
	return newListingAvailabilitiesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingAvailabilitiesTable(schemaName, tableName, alias string) *ListingAvailabilitiesTable {
	return &ListingAvailabilitiesTable{
		listingAvailabilitiesTable: newListingAvailabilitiesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newListingAvailabilitiesTableImpl("", "excluded", ""),
	}
}

func newListingAvailabilitiesTableImpl(schemaName, tableName, alias string) listingAvailabilitiesTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		AvailabilityIDColumn = postgres.IntegerColumn("availability_id")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		ListingIDColumn      = postgres.IntegerColumn("listing_id")
		allColumns           = postgres.ColumnList{IDColumn, AvailabilityIDColumn, CreatedAtColumn, UpdatedAtColumn, ListingIDColumn}
		mutableColumns       = postgres.ColumnList{AvailabilityIDColumn, CreatedAtColumn, UpdatedAtColumn, ListingIDColumn}
	)

	return listingAvailabilitiesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		AvailabilityID: AvailabilityIDColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		ListingID:      ListingIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
