//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingExtraFeatures = newListingExtraFeaturesTable("public", "listing_extra_features", "")

type listingExtraFeaturesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	ListingID postgres.ColumnInteger
	Available postgres.ColumnBool
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingExtraFeaturesTable struct {
	listingExtraFeaturesTable

	EXCLUDED listingExtraFeaturesTable
}

// AS creates new ListingExtraFeaturesTable with assigned alias
func (a ListingExtraFeaturesTable) AS(alias string) *ListingExtraFeaturesTable {
	return newListingExtraFeaturesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingExtraFeaturesTable with assigned schema name
func (a ListingExtraFeaturesTable) FromSchema(schemaName string) *ListingExtraFeaturesTable {
	return newListingExtraFeaturesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingExtraFeaturesTable with assigned table prefix
func (a ListingExtraFeaturesTable) WithPrefix(prefix string) *ListingExtraFeaturesTable {
	return newListingExtraFeaturesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingExtraFeaturesTable with assigned table suffix
func (a ListingExtraFeaturesTable) WithSuffix(suffix string) *ListingExtraFeaturesTable {
	return newListingExtraFeaturesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingExtraFeaturesTable(schemaName, tableName, alias string) *ListingExtraFeaturesTable {
	return &ListingExtraFeaturesTable{
		listingExtraFeaturesTable: newListingExtraFeaturesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newListingExtraFeaturesTableImpl("", "excluded", ""),
	}
}

func newListingExtraFeaturesTableImpl(schemaName, tableName, alias string) listingExtraFeaturesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		ListingIDColumn = postgres.IntegerColumn("listing_id")
		AvailableColumn = postgres.BoolColumn("available")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, ListingIDColumn, AvailableColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{ListingIDColumn, AvailableColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingExtraFeaturesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ListingID: ListingIDColumn,
		Available: AvailableColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
