//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingAvailabilityPrices = newListingAvailabilityPricesTable("public", "listing_availability_prices", "")

type listingAvailabilityPricesTable struct {
	postgres.Table

	// Columns
	ID                    postgres.ColumnInteger
	ListingAvailabilityID postgres.ColumnInteger
	Amount                postgres.ColumnFloat
	Currency              postgres.ColumnString
	CreatedAt             postgres.ColumnTimestamp
	UpdatedAt             postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingAvailabilityPricesTable struct {
	listingAvailabilityPricesTable

	EXCLUDED listingAvailabilityPricesTable
}

// AS creates new ListingAvailabilityPricesTable with assigned alias
func (a ListingAvailabilityPricesTable) AS(alias string) *ListingAvailabilityPricesTable {
	return newListingAvailabilityPricesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingAvailabilityPricesTable with assigned schema name
func (a ListingAvailabilityPricesTable) FromSchema(schemaName string) *ListingAvailabilityPricesTable {
	return newListingAvailabilityPricesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingAvailabilityPricesTable with assigned table prefix
func (a ListingAvailabilityPricesTable) WithPrefix(prefix string) *ListingAvailabilityPricesTable {
	return newListingAvailabilityPricesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingAvailabilityPricesTable with assigned table suffix
func (a ListingAvailabilityPricesTable) WithSuffix(suffix string) *ListingAvailabilityPricesTable {
	return newListingAvailabilityPricesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingAvailabilityPricesTable(schemaName, tableName, alias string) *ListingAvailabilityPricesTable {
	return &ListingAvailabilityPricesTable{
		listingAvailabilityPricesTable: newListingAvailabilityPricesTableImpl(schemaName, tableName, alias),
		EXCLUDED:                       newListingAvailabilityPricesTableImpl("", "excluded", ""),
	}
}

func newListingAvailabilityPricesTableImpl(schemaName, tableName, alias string) listingAvailabilityPricesTable {
	var (
		IDColumn                    = postgres.IntegerColumn("id")
		ListingAvailabilityIDColumn = postgres.IntegerColumn("listing_availability_id")
		AmountColumn                = postgres.FloatColumn("amount")
		CurrencyColumn              = postgres.StringColumn("currency")
		CreatedAtColumn             = postgres.TimestampColumn("created_at")
		UpdatedAtColumn             = postgres.TimestampColumn("updated_at")
		allColumns                  = postgres.ColumnList{IDColumn, ListingAvailabilityIDColumn, AmountColumn, CurrencyColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns              = postgres.ColumnList{ListingAvailabilityIDColumn, AmountColumn, CurrencyColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingAvailabilityPricesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		ListingAvailabilityID: ListingAvailabilityIDColumn,
		Amount:                AmountColumn,
		Currency:              CurrencyColumn,
		CreatedAt:             CreatedAtColumn,
		UpdatedAt:             UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
