//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingLocations = newListingLocationsTable("public", "listing_locations", "")

type listingLocationsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	CountryID postgres.ColumnInteger
	CityID    postgres.ColumnInteger
	AreaID    postgres.ColumnInteger
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingLocationsTable struct {
	listingLocationsTable

	EXCLUDED listingLocationsTable
}

// AS creates new ListingLocationsTable with assigned alias
func (a ListingLocationsTable) AS(alias string) *ListingLocationsTable {
	return newListingLocationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingLocationsTable with assigned schema name
func (a ListingLocationsTable) FromSchema(schemaName string) *ListingLocationsTable {
	return newListingLocationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingLocationsTable with assigned table prefix
func (a ListingLocationsTable) WithPrefix(prefix string) *ListingLocationsTable {
	return newListingLocationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingLocationsTable with assigned table suffix
func (a ListingLocationsTable) WithSuffix(suffix string) *ListingLocationsTable {
	return newListingLocationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingLocationsTable(schemaName, tableName, alias string) *ListingLocationsTable {
	return &ListingLocationsTable{
		listingLocationsTable: newListingLocationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newListingLocationsTableImpl("", "excluded", ""),
	}
}

func newListingLocationsTableImpl(schemaName, tableName, alias string) listingLocationsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CountryIDColumn = postgres.IntegerColumn("country_id")
		CityIDColumn    = postgres.IntegerColumn("city_id")
		AreaIDColumn    = postgres.IntegerColumn("area_id")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, CountryIDColumn, CityIDColumn, AreaIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CountryIDColumn, CityIDColumn, AreaIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingLocationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CountryID: CountryIDColumn,
		CityID:    CityIDColumn,
		AreaID:    AreaIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
