//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingPictures = newListingPicturesTable("public", "listing_pictures", "")

type listingPicturesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	ListingID   postgres.ColumnInteger
	URL         postgres.ColumnString
	Highlighted postgres.ColumnBool
	Title       postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingPicturesTable struct {
	listingPicturesTable

	EXCLUDED listingPicturesTable
}

// AS creates new ListingPicturesTable with assigned alias
func (a ListingPicturesTable) AS(alias string) *ListingPicturesTable {
	return newListingPicturesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingPicturesTable with assigned schema name
func (a ListingPicturesTable) FromSchema(schemaName string) *ListingPicturesTable {
	return newListingPicturesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingPicturesTable with assigned table prefix
func (a ListingPicturesTable) WithPrefix(prefix string) *ListingPicturesTable {
	return newListingPicturesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingPicturesTable with assigned table suffix
func (a ListingPicturesTable) WithSuffix(suffix string) *ListingPicturesTable {
	return newListingPicturesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingPicturesTable(schemaName, tableName, alias string) *ListingPicturesTable {
	return &ListingPicturesTable{
		listingPicturesTable: newListingPicturesTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newListingPicturesTableImpl("", "excluded", ""),
	}
}

func newListingPicturesTableImpl(schemaName, tableName, alias string) listingPicturesTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		ListingIDColumn   = postgres.IntegerColumn("listing_id")
		URLColumn         = postgres.StringColumn("url")
		HighlightedColumn = postgres.BoolColumn("highlighted")
		TitleColumn       = postgres.StringColumn("title")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, ListingIDColumn, URLColumn, HighlightedColumn, TitleColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{ListingIDColumn, URLColumn, HighlightedColumn, TitleColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingPicturesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		ListingID:   ListingIDColumn,
		URL:         URLColumn,
		Highlighted: HighlightedColumn,
		Title:       TitleColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
