//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Listings = newListingsTable("public", "listings", "")

type listingsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	TypeID     postgres.ColumnInteger
	AgencyID   postgres.ColumnInteger
	LocationID postgres.ColumnInteger
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp
	Slug       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingsTable struct {
	listingsTable

	EXCLUDED listingsTable
}

// AS creates new ListingsTable with assigned alias
func (a ListingsTable) AS(alias string) *ListingsTable {
	return newListingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingsTable with assigned schema name
func (a ListingsTable) FromSchema(schemaName string) *ListingsTable {
	return newListingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingsTable with assigned table prefix
func (a ListingsTable) WithPrefix(prefix string) *ListingsTable {
	return newListingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingsTable with assigned table suffix
func (a ListingsTable) WithSuffix(suffix string) *ListingsTable {
	return newListingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingsTable(schemaName, tableName, alias string) *ListingsTable {
	return &ListingsTable{
		listingsTable: newListingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newListingsTableImpl("", "excluded", ""),
	}
}

func newListingsTableImpl(schemaName, tableName, alias string) listingsTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		TypeIDColumn     = postgres.IntegerColumn("type_id")
		AgencyIDColumn   = postgres.IntegerColumn("agency_id")
		LocationIDColumn = postgres.IntegerColumn("location_id")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		SlugColumn       = postgres.StringColumn("slug")
		allColumns       = postgres.ColumnList{IDColumn, TypeIDColumn, AgencyIDColumn, LocationIDColumn, CreatedAtColumn, UpdatedAtColumn, SlugColumn}
		mutableColumns   = postgres.ColumnList{TypeIDColumn, AgencyIDColumn, LocationIDColumn, CreatedAtColumn, UpdatedAtColumn, SlugColumn}
	)

	return listingsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		TypeID:     TypeIDColumn,
		AgencyID:   AgencyIDColumn,
		LocationID: LocationIDColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,
		Slug:       SlugColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
