//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingTypesI18n = newListingTypesI18nTable("public", "listing_types_i18n", "")

type listingTypesI18nTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	LanguageCode  postgres.ColumnString
	ListingTypeID postgres.ColumnInteger
	Name          postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingTypesI18nTable struct {
	listingTypesI18nTable

	EXCLUDED listingTypesI18nTable
}

// AS creates new ListingTypesI18nTable with assigned alias
func (a ListingTypesI18nTable) AS(alias string) *ListingTypesI18nTable {
	return newListingTypesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingTypesI18nTable with assigned schema name
func (a ListingTypesI18nTable) FromSchema(schemaName string) *ListingTypesI18nTable {
	return newListingTypesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingTypesI18nTable with assigned table prefix
func (a ListingTypesI18nTable) WithPrefix(prefix string) *ListingTypesI18nTable {
	return newListingTypesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingTypesI18nTable with assigned table suffix
func (a ListingTypesI18nTable) WithSuffix(suffix string) *ListingTypesI18nTable {
	return newListingTypesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingTypesI18nTable(schemaName, tableName, alias string) *ListingTypesI18nTable {
	return &ListingTypesI18nTable{
		listingTypesI18nTable: newListingTypesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newListingTypesI18nTableImpl("", "excluded", ""),
	}
}

func newListingTypesI18nTableImpl(schemaName, tableName, alias string) listingTypesI18nTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		LanguageCodeColumn  = postgres.StringColumn("language_code")
		ListingTypeIDColumn = postgres.IntegerColumn("listing_type_id")
		NameColumn          = postgres.StringColumn("name")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, LanguageCodeColumn, ListingTypeIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{LanguageCodeColumn, ListingTypeIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingTypesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		LanguageCode:  LanguageCodeColumn,
		ListingTypeID: ListingTypeIDColumn,
		Name:          NameColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
