//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ListingsI18n = newListingsI18nTable("public", "listings_i18n", "")

type listingsI18nTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	LanguageCode postgres.ColumnString
	ListingID    postgres.ColumnInteger
	Description  postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ListingsI18nTable struct {
	listingsI18nTable

	EXCLUDED listingsI18nTable
}

// AS creates new ListingsI18nTable with assigned alias
func (a ListingsI18nTable) AS(alias string) *ListingsI18nTable {
	return newListingsI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ListingsI18nTable with assigned schema name
func (a ListingsI18nTable) FromSchema(schemaName string) *ListingsI18nTable {
	return newListingsI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ListingsI18nTable with assigned table prefix
func (a ListingsI18nTable) WithPrefix(prefix string) *ListingsI18nTable {
	return newListingsI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ListingsI18nTable with assigned table suffix
func (a ListingsI18nTable) WithSuffix(suffix string) *ListingsI18nTable {
	return newListingsI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newListingsI18nTable(schemaName, tableName, alias string) *ListingsI18nTable {
	return &ListingsI18nTable{
		listingsI18nTable: newListingsI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newListingsI18nTableImpl("", "excluded", ""),
	}
}

func newListingsI18nTableImpl(schemaName, tableName, alias string) listingsI18nTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		LanguageCodeColumn = postgres.StringColumn("language_code")
		ListingIDColumn    = postgres.IntegerColumn("listing_id")
		DescriptionColumn  = postgres.StringColumn("description")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, LanguageCodeColumn, ListingIDColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{LanguageCodeColumn, ListingIDColumn, DescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return listingsI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		LanguageCode: LanguageCodeColumn,
		ListingID:    ListingIDColumn,
		Description:  DescriptionColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
