//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Otps = newOtpsTable("public", "otps", "")

type otpsTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	UserID     postgres.ColumnInteger
	Code       postgres.ColumnString
	SentAt     postgres.ColumnTimestamp
	VerifiedAt postgres.ColumnTimestamp
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type OtpsTable struct {
	otpsTable

	EXCLUDED otpsTable
}

// AS creates new OtpsTable with assigned alias
func (a OtpsTable) AS(alias string) *OtpsTable {
	return newOtpsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OtpsTable with assigned schema name
func (a OtpsTable) FromSchema(schemaName string) *OtpsTable {
	return newOtpsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OtpsTable with assigned table prefix
func (a OtpsTable) WithPrefix(prefix string) *OtpsTable {
	return newOtpsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OtpsTable with assigned table suffix
func (a OtpsTable) WithSuffix(suffix string) *OtpsTable {
	return newOtpsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOtpsTable(schemaName, tableName, alias string) *OtpsTable {
	return &OtpsTable{
		otpsTable: newOtpsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newOtpsTableImpl("", "excluded", ""),
	}
}

func newOtpsTableImpl(schemaName, tableName, alias string) otpsTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		UserIDColumn     = postgres.IntegerColumn("user_id")
		CodeColumn       = postgres.StringColumn("code")
		SentAtColumn     = postgres.TimestampColumn("sent_at")
		VerifiedAtColumn = postgres.TimestampColumn("verified_at")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, UserIDColumn, CodeColumn, SentAtColumn, VerifiedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{UserIDColumn, CodeColumn, SentAtColumn, VerifiedAtColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return otpsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		UserID:     UserIDColumn,
		Code:       CodeColumn,
		SentAt:     SentAtColumn,
		VerifiedAt: VerifiedAtColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
