//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Properties = newPropertiesTable("public", "properties", "")

type propertiesTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnInteger
	ListingID        postgres.ColumnInteger
	Bedrooms         postgres.ColumnInteger
	Bathrooms        postgres.ColumnInteger
	Area             postgres.ColumnFloat
	Furnished        postgres.ColumnBool
	YearBuilt        postgres.ColumnInteger
	PropertyStatusID postgres.ColumnInteger
	CreatedAt        postgres.ColumnTimestamp
	UpdatedAt        postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PropertiesTable struct {
	propertiesTable

	EXCLUDED propertiesTable
}

// AS creates new PropertiesTable with assigned alias
func (a PropertiesTable) AS(alias string) *PropertiesTable {
	return newPropertiesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PropertiesTable with assigned schema name
func (a PropertiesTable) FromSchema(schemaName string) *PropertiesTable {
	return newPropertiesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PropertiesTable with assigned table prefix
func (a PropertiesTable) WithPrefix(prefix string) *PropertiesTable {
	return newPropertiesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PropertiesTable with assigned table suffix
func (a PropertiesTable) WithSuffix(suffix string) *PropertiesTable {
	return newPropertiesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPropertiesTable(schemaName, tableName, alias string) *PropertiesTable {
	return &PropertiesTable{
		propertiesTable: newPropertiesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newPropertiesTableImpl("", "excluded", ""),
	}
}

func newPropertiesTableImpl(schemaName, tableName, alias string) propertiesTable {
	var (
		IDColumn               = postgres.IntegerColumn("id")
		ListingIDColumn        = postgres.IntegerColumn("listing_id")
		BedroomsColumn         = postgres.IntegerColumn("bedrooms")
		BathroomsColumn        = postgres.IntegerColumn("bathrooms")
		AreaColumn             = postgres.FloatColumn("area")
		FurnishedColumn        = postgres.BoolColumn("furnished")
		YearBuiltColumn        = postgres.IntegerColumn("year_built")
		PropertyStatusIDColumn = postgres.IntegerColumn("property_status_id")
		CreatedAtColumn        = postgres.TimestampColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampColumn("updated_at")
		allColumns             = postgres.ColumnList{IDColumn, ListingIDColumn, BedroomsColumn, BathroomsColumn, AreaColumn, FurnishedColumn, YearBuiltColumn, PropertyStatusIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = postgres.ColumnList{ListingIDColumn, BedroomsColumn, BathroomsColumn, AreaColumn, FurnishedColumn, YearBuiltColumn, PropertyStatusIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return propertiesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		ListingID:        ListingIDColumn,
		Bedrooms:         BedroomsColumn,
		Bathrooms:        BathroomsColumn,
		Area:             AreaColumn,
		Furnished:        FurnishedColumn,
		YearBuilt:        YearBuiltColumn,
		PropertyStatusID: PropertyStatusIDColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
