//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PropertyStatuses = newPropertyStatusesTable("public", "property_statuses", "")

type propertyStatusesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Code      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PropertyStatusesTable struct {
	propertyStatusesTable

	EXCLUDED propertyStatusesTable
}

// AS creates new PropertyStatusesTable with assigned alias
func (a PropertyStatusesTable) AS(alias string) *PropertyStatusesTable {
	return newPropertyStatusesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PropertyStatusesTable with assigned schema name
func (a PropertyStatusesTable) FromSchema(schemaName string) *PropertyStatusesTable {
	return newPropertyStatusesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PropertyStatusesTable with assigned table prefix
func (a PropertyStatusesTable) WithPrefix(prefix string) *PropertyStatusesTable {
	return newPropertyStatusesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PropertyStatusesTable with assigned table suffix
func (a PropertyStatusesTable) WithSuffix(suffix string) *PropertyStatusesTable {
	return newPropertyStatusesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPropertyStatusesTable(schemaName, tableName, alias string) *PropertyStatusesTable {
	return &PropertyStatusesTable{
		propertyStatusesTable: newPropertyStatusesTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newPropertyStatusesTableImpl("", "excluded", ""),
	}
}

func newPropertyStatusesTableImpl(schemaName, tableName, alias string) propertyStatusesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CodeColumn      = postgres.StringColumn("code")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, CodeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{CodeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return propertyStatusesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Code:      CodeColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
