//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PropertiesI18n = newPropertiesI18nTable("public", "properties_i18n", "")

type propertiesI18nTable struct {
	postgres.Table

	// Columns
	ID                   postgres.ColumnInteger
	LanguageCode         postgres.ColumnString
	PropertyID           postgres.ColumnInteger
	BedroomsDescription  postgres.ColumnString
	BathroomsDescription postgres.ColumnString
	AreaDescription      postgres.ColumnString
	FurnishedDescription postgres.ColumnString
	YearBuiltDescription postgres.ColumnString
	CreatedAt            postgres.ColumnTimestamp
	UpdatedAt            postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PropertiesI18nTable struct {
	propertiesI18nTable

	EXCLUDED propertiesI18nTable
}

// AS creates new PropertiesI18nTable with assigned alias
func (a PropertiesI18nTable) AS(alias string) *PropertiesI18nTable {
	return newPropertiesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PropertiesI18nTable with assigned schema name
func (a PropertiesI18nTable) FromSchema(schemaName string) *PropertiesI18nTable {
	return newPropertiesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PropertiesI18nTable with assigned table prefix
func (a PropertiesI18nTable) WithPrefix(prefix string) *PropertiesI18nTable {
	return newPropertiesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PropertiesI18nTable with assigned table suffix
func (a PropertiesI18nTable) WithSuffix(suffix string) *PropertiesI18nTable {
	return newPropertiesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPropertiesI18nTable(schemaName, tableName, alias string) *PropertiesI18nTable {
	return &PropertiesI18nTable{
		propertiesI18nTable: newPropertiesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newPropertiesI18nTableImpl("", "excluded", ""),
	}
}

func newPropertiesI18nTableImpl(schemaName, tableName, alias string) propertiesI18nTable {
	var (
		IDColumn                   = postgres.IntegerColumn("id")
		LanguageCodeColumn         = postgres.StringColumn("language_code")
		PropertyIDColumn           = postgres.IntegerColumn("property_id")
		BedroomsDescriptionColumn  = postgres.StringColumn("bedrooms_description")
		BathroomsDescriptionColumn = postgres.StringColumn("bathrooms_description")
		AreaDescriptionColumn      = postgres.StringColumn("area_description")
		FurnishedDescriptionColumn = postgres.StringColumn("furnished_description")
		YearBuiltDescriptionColumn = postgres.StringColumn("year_built_description")
		CreatedAtColumn            = postgres.TimestampColumn("created_at")
		UpdatedAtColumn            = postgres.TimestampColumn("updated_at")
		allColumns                 = postgres.ColumnList{IDColumn, LanguageCodeColumn, PropertyIDColumn, BedroomsDescriptionColumn, BathroomsDescriptionColumn, AreaDescriptionColumn, FurnishedDescriptionColumn, YearBuiltDescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns             = postgres.ColumnList{LanguageCodeColumn, PropertyIDColumn, BedroomsDescriptionColumn, BathroomsDescriptionColumn, AreaDescriptionColumn, FurnishedDescriptionColumn, YearBuiltDescriptionColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return propertiesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		LanguageCode:         LanguageCodeColumn,
		PropertyID:           PropertyIDColumn,
		BedroomsDescription:  BedroomsDescriptionColumn,
		BathroomsDescription: BathroomsDescriptionColumn,
		AreaDescription:      AreaDescriptionColumn,
		FurnishedDescription: FurnishedDescriptionColumn,
		YearBuiltDescription: YearBuiltDescriptionColumn,
		CreatedAt:            CreatedAtColumn,
		UpdatedAt:            UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
