//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SeedersDbVersion = newSeedersDbVersionTable("public", "seeders_db_version", "")

type seedersDbVersionTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	VersionID postgres.ColumnInteger
	IsApplied postgres.ColumnBool
	Tstamp    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SeedersDbVersionTable struct {
	seedersDbVersionTable

	EXCLUDED seedersDbVersionTable
}

// AS creates new SeedersDbVersionTable with assigned alias
func (a SeedersDbVersionTable) AS(alias string) *SeedersDbVersionTable {
	return newSeedersDbVersionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SeedersDbVersionTable with assigned schema name
func (a SeedersDbVersionTable) FromSchema(schemaName string) *SeedersDbVersionTable {
	return newSeedersDbVersionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SeedersDbVersionTable with assigned table prefix
func (a SeedersDbVersionTable) WithPrefix(prefix string) *SeedersDbVersionTable {
	return newSeedersDbVersionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SeedersDbVersionTable with assigned table suffix
func (a SeedersDbVersionTable) WithSuffix(suffix string) *SeedersDbVersionTable {
	return newSeedersDbVersionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSeedersDbVersionTable(schemaName, tableName, alias string) *SeedersDbVersionTable {
	return &SeedersDbVersionTable{
		seedersDbVersionTable: newSeedersDbVersionTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newSeedersDbVersionTableImpl("", "excluded", ""),
	}
}

func newSeedersDbVersionTableImpl(schemaName, tableName, alias string) seedersDbVersionTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		VersionIDColumn = postgres.IntegerColumn("version_id")
		IsAppliedColumn = postgres.BoolColumn("is_applied")
		TstampColumn    = postgres.TimestampColumn("tstamp")
		allColumns      = postgres.ColumnList{IDColumn, VersionIDColumn, IsAppliedColumn, TstampColumn}
		mutableColumns  = postgres.ColumnList{VersionIDColumn, IsAppliedColumn, TstampColumn}
	)

	return seedersDbVersionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		VersionID: VersionIDColumn,
		IsApplied: IsAppliedColumn,
		Tstamp:    TstampColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
