//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Agencies = Agencies.FromSchema(schema)
	AgenciesI18n = AgenciesI18n.FromSchema(schema)
	AgencyAgents = AgencyAgents.FromSchema(schema)
	AgencyPhoneNumbers = AgencyPhoneNumbers.FromSchema(schema)
	AgencyReviews = AgencyReviews.FromSchema(schema)
	Areas = Areas.FromSchema(schema)
	AreasI18n = AreasI18n.FromSchema(schema)
	Availabilities = Availabilities.FromSchema(schema)
	Cities = Cities.FromSchema(schema)
	CitiesI18n = CitiesI18n.FromSchema(schema)
	ConversationMessages = ConversationMessages.FromSchema(schema)
	Conversations = Conversations.FromSchema(schema)
	Countries = Countries.FromSchema(schema)
	CountriesI18n = CountriesI18n.FromSchema(schema)
	CustomerFavoriteListings = CustomerFavoriteListings.FromSchema(schema)
	CustomerFollowedAgencies = CustomerFollowedAgencies.FromSchema(schema)
	Customers = Customers.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	ListingAvailabilities = ListingAvailabilities.FromSchema(schema)
	ListingAvailabilityPrices = ListingAvailabilityPrices.FromSchema(schema)
	ListingExtraFeatures = ListingExtraFeatures.FromSchema(schema)
	ListingExtraFeaturesI18n = ListingExtraFeaturesI18n.FromSchema(schema)
	ListingLocations = ListingLocations.FromSchema(schema)
	ListingPictures = ListingPictures.FromSchema(schema)
	ListingTypes = ListingTypes.FromSchema(schema)
	ListingTypesI18n = ListingTypesI18n.FromSchema(schema)
	Listings = Listings.FromSchema(schema)
	ListingsI18n = ListingsI18n.FromSchema(schema)
	Otps = Otps.FromSchema(schema)
	Properties = Properties.FromSchema(schema)
	PropertiesI18n = PropertiesI18n.FromSchema(schema)
	PropertyStatuses = PropertyStatuses.FromSchema(schema)
	SeedersDbVersion = SeedersDbVersion.FromSchema(schema)
	Uploads = Uploads.FromSchema(schema)
	UserPhoneNumbers = UserPhoneNumbers.FromSchema(schema)
	UserRoles = UserRoles.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
