//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Uploads = newUploadsTable("public", "uploads", "")

type uploadsTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnInteger
	UserID           postgres.ColumnInteger
	File             postgres.ColumnString
	OriginalFileName postgres.ColumnString
	FileType         postgres.ColumnString
	CreatedAt        postgres.ColumnTimestamp
	UpdatedAt        postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UploadsTable struct {
	uploadsTable

	EXCLUDED uploadsTable
}

// AS creates new UploadsTable with assigned alias
func (a UploadsTable) AS(alias string) *UploadsTable {
	return newUploadsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UploadsTable with assigned schema name
func (a UploadsTable) FromSchema(schemaName string) *UploadsTable {
	return newUploadsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UploadsTable with assigned table prefix
func (a UploadsTable) WithPrefix(prefix string) *UploadsTable {
	return newUploadsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UploadsTable with assigned table suffix
func (a UploadsTable) WithSuffix(suffix string) *UploadsTable {
	return newUploadsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUploadsTable(schemaName, tableName, alias string) *UploadsTable {
	return &UploadsTable{
		uploadsTable: newUploadsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newUploadsTableImpl("", "excluded", ""),
	}
}

func newUploadsTableImpl(schemaName, tableName, alias string) uploadsTable {
	var (
		IDColumn               = postgres.IntegerColumn("id")
		UserIDColumn           = postgres.IntegerColumn("user_id")
		FileColumn             = postgres.StringColumn("file")
		OriginalFileNameColumn = postgres.StringColumn("original_file_name")
		FileTypeColumn         = postgres.StringColumn("file_type")
		CreatedAtColumn        = postgres.TimestampColumn("created_at")
		UpdatedAtColumn        = postgres.TimestampColumn("updated_at")
		allColumns             = postgres.ColumnList{IDColumn, UserIDColumn, FileColumn, OriginalFileNameColumn, FileTypeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns         = postgres.ColumnList{UserIDColumn, FileColumn, OriginalFileNameColumn, FileTypeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return uploadsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		UserID:           UserIDColumn,
		File:             FileColumn,
		OriginalFileName: OriginalFileNameColumn,
		FileType:         FileTypeColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
