//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserPhoneNumbers = newUserPhoneNumbersTable("public", "user_phone_numbers", "")

type userPhoneNumbersTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	UserID      postgres.ColumnInteger
	CountryCode postgres.ColumnString
	PhoneNumber postgres.ColumnString
	CreatedAt   postgres.ColumnTimestamp
	UpdatedAt   postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UserPhoneNumbersTable struct {
	userPhoneNumbersTable

	EXCLUDED userPhoneNumbersTable
}

// AS creates new UserPhoneNumbersTable with assigned alias
func (a UserPhoneNumbersTable) AS(alias string) *UserPhoneNumbersTable {
	return newUserPhoneNumbersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserPhoneNumbersTable with assigned schema name
func (a UserPhoneNumbersTable) FromSchema(schemaName string) *UserPhoneNumbersTable {
	return newUserPhoneNumbersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserPhoneNumbersTable with assigned table prefix
func (a UserPhoneNumbersTable) WithPrefix(prefix string) *UserPhoneNumbersTable {
	return newUserPhoneNumbersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserPhoneNumbersTable with assigned table suffix
func (a UserPhoneNumbersTable) WithSuffix(suffix string) *UserPhoneNumbersTable {
	return newUserPhoneNumbersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserPhoneNumbersTable(schemaName, tableName, alias string) *UserPhoneNumbersTable {
	return &UserPhoneNumbersTable{
		userPhoneNumbersTable: newUserPhoneNumbersTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newUserPhoneNumbersTableImpl("", "excluded", ""),
	}
}

func newUserPhoneNumbersTableImpl(schemaName, tableName, alias string) userPhoneNumbersTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		UserIDColumn      = postgres.IntegerColumn("user_id")
		CountryCodeColumn = postgres.StringColumn("country_code")
		PhoneNumberColumn = postgres.StringColumn("phone_number")
		CreatedAtColumn   = postgres.TimestampColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, UserIDColumn, CountryCodeColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{UserIDColumn, CountryCodeColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return userPhoneNumbersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		UserID:      UserIDColumn,
		CountryCode: CountryCodeColumn,
		PhoneNumber: PhoneNumberColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
