//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Users = newUsersTable("public", "users", "")

type usersTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	Name           postgres.ColumnString
	EmailAddress   postgres.ColumnString
	Active         postgres.ColumnBool
	ProfilePicture postgres.ColumnString
	Role           postgres.ColumnInteger
	LastLoginAt    postgres.ColumnTimestamp
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp
	Verified       postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		NameColumn           = postgres.StringColumn("name")
		EmailAddressColumn   = postgres.StringColumn("email_address")
		ActiveColumn         = postgres.BoolColumn("active")
		ProfilePictureColumn = postgres.StringColumn("profile_picture")
		RoleColumn           = postgres.IntegerColumn("role")
		LastLoginAtColumn    = postgres.TimestampColumn("last_login_at")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		VerifiedColumn       = postgres.BoolColumn("verified")
		allColumns           = postgres.ColumnList{IDColumn, NameColumn, EmailAddressColumn, ActiveColumn, ProfilePictureColumn, RoleColumn, LastLoginAtColumn, CreatedAtColumn, UpdatedAtColumn, VerifiedColumn}
		mutableColumns       = postgres.ColumnList{NameColumn, EmailAddressColumn, ActiveColumn, ProfilePictureColumn, RoleColumn, LastLoginAtColumn, CreatedAtColumn, UpdatedAtColumn, VerifiedColumn}
	)

	return usersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		Name:           NameColumn,
		EmailAddress:   EmailAddressColumn,
		Active:         ActiveColumn,
		ProfilePicture: ProfilePictureColumn,
		Role:           RoleColumn,
		LastLoginAt:    LastLoginAtColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		Verified:       VerifiedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
