//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Agencies struct {
	ID           int64     `sql:"primary_key" json:"id,omitempty"`
	Slug         string    `json:"slug,omitempty"`
	EmailAddress string    `json:"emailAddress,omitempty"`
	Logo         string    `json:"logo,omitempty"`
	CreatedAt    time.Time `json:"createdAt,omitempty"`
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
}
