//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AreasI18n struct {
	ID           int64     `sql:"primary_key" json:"id,omitempty"`
	LanguageCode string    `json:"languageCode,omitempty"`
	AreaID       int64     `json:"areaID,omitempty"`
	Name         string    `json:"name,omitempty"`
	CreatedAt    time.Time `json:"createdAt,omitempty"`
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
}
