//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ConversationMessages struct {
	ID             int64       `sql:"primary_key" json:"id,omitempty"`
	ConversationID int64       `json:"conversationID,omitempty"`
	Type           Messagetype `json:"type,omitempty"`
	Sender         Sendertype  `json:"sender,omitempty"`
	TextContent    *string     `json:"textContent,omitempty"`
	CreatedAt      time.Time   `json:"createdAt,omitempty"`
	UpdatedAt      time.Time   `json:"updatedAt,omitempty"`
}
