//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CustomerFollowedAgencies struct {
	ID         int64     `sql:"primary_key" json:"id,omitempty"`
	CustomerID int64     `json:"customerID,omitempty"`
	AgencyID   int64     `json:"agencyID,omitempty"`
	CreatedAt  time.Time `json:"createdAt,omitempty"`
	UpdatedAt  time.Time `json:"updatedAt,omitempty"`
}
