//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ListingAvailabilityPrices struct {
	ID                    int64     `sql:"primary_key" json:"id,omitempty"`
	ListingAvailabilityID int64     `json:"listingAvailabilityID,omitempty"`
	Amount                float64   `json:"amount,omitempty"`
	Currency              string    `json:"currency,omitempty"`
	CreatedAt             time.Time `json:"createdAt,omitempty"`
	UpdatedAt             time.Time `json:"updatedAt,omitempty"`
}
