//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ListingExtraFeaturesI18n struct {
	ID                     int64     `sql:"primary_key" json:"id,omitempty"`
	ListingExtraFeaturesID int64     `json:"listingExtraFeaturesID,omitempty"`
	LanguageCode           string    `json:"languageCode,omitempty"`
	Title                  string    `json:"title,omitempty"`
	CreatedAt              time.Time `json:"createdAt,omitempty"`
	UpdatedAt              time.Time `json:"updatedAt,omitempty"`
}
