//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ListingLocations struct {
	ID        int64     `sql:"primary_key" json:"id,omitempty"`
	CountryID int64     `json:"countryID,omitempty"`
	CityID    int64     `json:"cityID,omitempty"`
	AreaID    int64     `json:"areaID,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
