//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ListingTypes struct {
	ID           int64     `sql:"primary_key" json:"id,omitempty"`
	ParentTypeID *int64    `json:"parentTypeID,omitempty"`
	Code         string    `json:"code,omitempty"`
	CreatedAt    time.Time `json:"createdAt,omitempty"`
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
}
