//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ListingPictures struct {
	ID          int64     `sql:"primary_key" json:"id,omitempty"`
	ListingID   int64     `json:"listingID,omitempty"`
	URL         string    `json:"url,omitempty"`
	Highlighted *bool     `json:"highlighted,omitempty"`
	Title       *string   `json:"title,omitempty"`
	CreatedAt   time.Time `json:"createdAt,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt,omitempty"`
}
