//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Messagetype string

const (
	Messagetype_Text Messagetype = "TEXT"
)

func (e *Messagetype) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "TEXT":
		*e = Messagetype_Text
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Messagetype enum")
	}

	return nil
}

func (e Messagetype) String() string {
	return string(e)
}
