//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Properties struct {
	ID               int64     `sql:"primary_key" json:"id,omitempty"`
	ListingID        int64     `json:"listingID,omitempty"`
	Bedrooms         int32     `json:"bedrooms,omitempty"`
	Bathrooms        int32     `json:"bathrooms,omitempty"`
	Area             float64   `json:"area,omitempty"`
	Furnished        bool      `json:"furnished,omitempty"`
	YearBuilt        int32     `json:"yearBuilt,omitempty"`
	PropertyStatusID int64     `json:"propertyStatusID,omitempty"`
	CreatedAt        time.Time `json:"createdAt,omitempty"`
	UpdatedAt        time.Time `json:"updatedAt,omitempty"`
}
