//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PropertiesI18n struct {
	ID                   int64     `sql:"primary_key" json:"id,omitempty"`
	LanguageCode         string    `json:"languageCode,omitempty"`
	PropertyID           int64     `json:"propertyID,omitempty"`
	BedroomsDescription  *string   `json:"bedroomsDescription,omitempty"`
	BathroomsDescription *string   `json:"bathroomsDescription,omitempty"`
	AreaDescription      *string   `json:"areaDescription,omitempty"`
	FurnishedDescription *string   `json:"furnishedDescription,omitempty"`
	YearBuiltDescription *string   `json:"yearBuiltDescription,omitempty"`
	CreatedAt            time.Time `json:"createdAt,omitempty"`
	UpdatedAt            time.Time `json:"updatedAt,omitempty"`
}
