//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Sendertype string

const (
	Sendertype_Customer Sendertype = "CUSTOMER"
	Sendertype_Agency   Sendertype = "AGENCY"
)

func (e *Sendertype) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "CUSTOMER":
		*e = Sendertype_Customer
	case "AGENCY":
		*e = Sendertype_Agency
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Sendertype enum")
	}

	return nil
}

func (e Sendertype) String() string {
	return string(e)
}
