//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Uploads struct {
	ID               int64     `sql:"primary_key" json:"id,omitempty"`
	UserID           int64     `json:"userID,omitempty"`
	File             string    `json:"file,omitempty"`
	OriginalFileName *string   `json:"originalFileName,omitempty"`
	FileType         *string   `json:"fileType,omitempty"`
	CreatedAt        time.Time `json:"createdAt,omitempty"`
	UpdatedAt        time.Time `json:"updatedAt,omitempty"`
}
