//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID             int64      `sql:"primary_key" json:"id,omitempty"`
	Name           string     `json:"name,omitempty"`
	EmailAddress   string     `json:"emailAddress,omitempty"`
	Active         bool       `json:"active,omitempty"`
	ProfilePicture *string    `json:"profilePicture,omitempty"`
	Role           int64      `json:"role,omitempty"`
	LastLoginAt    *time.Time `json:"lastLoginAt,omitempty"`
	CreatedAt      time.Time  `json:"createdAt,omitempty"`
	UpdatedAt      time.Time  `json:"updatedAt,omitempty"`
	Verified       bool       `json:"verified,omitempty"`
}
