// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package conversations

import (
	"database/sql"
)

// Injectors from wire.go:

func Init(database *sql.DB) *handler {
	conversationsRepo := NewRepo(database)
	conversationsService := NewService(conversationsRepo)
	conversationsHandler := NewHandler(conversationsService)
	return conversationsHandler
}
