//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Amenities struct {
	ID         int64     `sql:"primary_key" json:"id,omitempty"`
	Icon       string    `json:"icon,omitempty"`
	IsRequired bool      `json:"isRequired,omitempty"`
	CreatedAt  time.Time `json:"createdAt,omitempty"`
	UpdatedAt  time.Time `json:"updatedAt,omitempty"`
}
