//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CoreFeaturesI18n struct {
	ID            int64     `sql:"primary_key" json:"id,omitempty"`
	CoreFeatureID int64     `json:"coreFeatureID,omitempty"`
	Name          string    `json:"name,omitempty"`
	Description   string    `json:"description,omitempty"`
	LanguageCode  string    `json:"languageCode,omitempty"`
	CreatedAt     time.Time `json:"createdAt,omitempty"`
	UpdatedAt     time.Time `json:"updatedAt,omitempty"`
}
