//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CoreFeatures struct {
	ID        int64     `sql:"primary_key" json:"id,omitempty"`
	Icon      string    `json:"icon,omitempty"`
	Required  bool      `json:"required,omitempty"`
	DataType  Datatype  `json:"dataType,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
