//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Datatype string

const (
	Datatype_Text   Datatype = "text"
	Datatype_Number Datatype = "number"
)

func (e *Datatype) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "text":
		*e = Datatype_Text
	case "number":
		*e = Datatype_Number
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Datatype enum")
	}

	return nil
}

func (e Datatype) String() string {
	return string(e)
}
