//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type GooseDbVersion struct {
	ID        int32      `sql:"primary_key" json:"id,omitempty"`
	VersionID int64      `json:"versionID,omitempty"`
	IsApplied bool       `json:"isApplied,omitempty"`
	Tstamp    *time.Time `json:"tstamp,omitempty"`
}
