// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package users

import (
	"database/sql"
)

// Injectors from wire.go:

func Init(database *sql.DB) *handler {
	usersRepo := NewRepo(database)
	usersService := NewService(usersRepo)
	usersHandler := NewHandler(usersService)
	return usersHandler
}
