//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AgenciesI18n = newAgenciesI18nTable("public", "agencies_i18n", "")

type agenciesI18nTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnInteger
	Agency      postgres.ColumnInteger
	LocaleCode  postgres.ColumnString
	Name        postgres.ColumnString
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AgenciesI18nTable struct {
	agenciesI18nTable

	EXCLUDED agenciesI18nTable
}

// AS creates new AgenciesI18nTable with assigned alias
func (a AgenciesI18nTable) AS(alias string) *AgenciesI18nTable {
	return newAgenciesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AgenciesI18nTable with assigned schema name
func (a AgenciesI18nTable) FromSchema(schemaName string) *AgenciesI18nTable {
	return newAgenciesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AgenciesI18nTable with assigned table prefix
func (a AgenciesI18nTable) WithPrefix(prefix string) *AgenciesI18nTable {
	return newAgenciesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AgenciesI18nTable with assigned table suffix
func (a AgenciesI18nTable) WithSuffix(suffix string) *AgenciesI18nTable {
	return newAgenciesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAgenciesI18nTable(schemaName, tableName, alias string) *AgenciesI18nTable {
	return &AgenciesI18nTable{
		agenciesI18nTable: newAgenciesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newAgenciesI18nTableImpl("", "excluded", ""),
	}
}

func newAgenciesI18nTableImpl(schemaName, tableName, alias string) agenciesI18nTable {
	var (
		IDColumn          = postgres.IntegerColumn("id")
		AgencyColumn      = postgres.IntegerColumn("agency")
		LocaleCodeColumn  = postgres.StringColumn("locale_code")
		NameColumn        = postgres.StringColumn("name")
		DescriptionColumn = postgres.StringColumn("description")
		allColumns        = postgres.ColumnList{IDColumn, AgencyColumn, LocaleCodeColumn, NameColumn, DescriptionColumn}
		mutableColumns    = postgres.ColumnList{AgencyColumn, LocaleCodeColumn, NameColumn, DescriptionColumn}
	)

	return agenciesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Agency:      AgencyColumn,
		LocaleCode:  LocaleCodeColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
