//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AmenitiesI18n = newAmenitiesI18nTable("public", "amenities_i18n", "")

type amenitiesI18nTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnInteger
	AmenityID    postgres.ColumnInteger
	Title        postgres.ColumnString
	LanguageCode postgres.ColumnString
	CreatedAt    postgres.ColumnTimestamp
	UpdatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AmenitiesI18nTable struct {
	amenitiesI18nTable

	EXCLUDED amenitiesI18nTable
}

// AS creates new AmenitiesI18nTable with assigned alias
func (a AmenitiesI18nTable) AS(alias string) *AmenitiesI18nTable {
	return newAmenitiesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AmenitiesI18nTable with assigned schema name
func (a AmenitiesI18nTable) FromSchema(schemaName string) *AmenitiesI18nTable {
	return newAmenitiesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AmenitiesI18nTable with assigned table prefix
func (a AmenitiesI18nTable) WithPrefix(prefix string) *AmenitiesI18nTable {
	return newAmenitiesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AmenitiesI18nTable with assigned table suffix
func (a AmenitiesI18nTable) WithSuffix(suffix string) *AmenitiesI18nTable {
	return newAmenitiesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAmenitiesI18nTable(schemaName, tableName, alias string) *AmenitiesI18nTable {
	return &AmenitiesI18nTable{
		amenitiesI18nTable: newAmenitiesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAmenitiesI18nTableImpl("", "excluded", ""),
	}
}

func newAmenitiesI18nTableImpl(schemaName, tableName, alias string) amenitiesI18nTable {
	var (
		IDColumn           = postgres.IntegerColumn("id")
		AmenityIDColumn    = postgres.IntegerColumn("amenity_id")
		TitleColumn        = postgres.StringColumn("title")
		LanguageCodeColumn = postgres.StringColumn("language_code")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		UpdatedAtColumn    = postgres.TimestampColumn("updated_at")
		allColumns         = postgres.ColumnList{IDColumn, AmenityIDColumn, TitleColumn, LanguageCodeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns     = postgres.ColumnList{AmenityIDColumn, TitleColumn, LanguageCodeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return amenitiesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		AmenityID:    AmenityIDColumn,
		Title:        TitleColumn,
		LanguageCode: LanguageCodeColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
