//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Amenities = newAmenitiesTable("public", "amenities", "")

type amenitiesTable struct {
	postgres.Table

	// Columns
	ID         postgres.ColumnInteger
	Icon       postgres.ColumnString
	IsRequired postgres.ColumnBool
	CreatedAt  postgres.ColumnTimestamp
	UpdatedAt  postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AmenitiesTable struct {
	amenitiesTable

	EXCLUDED amenitiesTable
}

// AS creates new AmenitiesTable with assigned alias
func (a AmenitiesTable) AS(alias string) *AmenitiesTable {
	return newAmenitiesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AmenitiesTable with assigned schema name
func (a AmenitiesTable) FromSchema(schemaName string) *AmenitiesTable {
	return newAmenitiesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AmenitiesTable with assigned table prefix
func (a AmenitiesTable) WithPrefix(prefix string) *AmenitiesTable {
	return newAmenitiesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AmenitiesTable with assigned table suffix
func (a AmenitiesTable) WithSuffix(suffix string) *AmenitiesTable {
	return newAmenitiesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAmenitiesTable(schemaName, tableName, alias string) *AmenitiesTable {
	return &AmenitiesTable{
		amenitiesTable: newAmenitiesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newAmenitiesTableImpl("", "excluded", ""),
	}
}

func newAmenitiesTableImpl(schemaName, tableName, alias string) amenitiesTable {
	var (
		IDColumn         = postgres.IntegerColumn("id")
		IconColumn       = postgres.StringColumn("icon")
		IsRequiredColumn = postgres.BoolColumn("is_required")
		CreatedAtColumn  = postgres.TimestampColumn("created_at")
		UpdatedAtColumn  = postgres.TimestampColumn("updated_at")
		allColumns       = postgres.ColumnList{IDColumn, IconColumn, IsRequiredColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = postgres.ColumnList{IconColumn, IsRequiredColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return amenitiesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		Icon:       IconColumn,
		IsRequired: IsRequiredColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
