//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CoreFeatures = newCoreFeaturesTable("public", "core_features", "")

type coreFeaturesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Icon      postgres.ColumnString
	Required  postgres.ColumnBool
	DataType  postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CoreFeaturesTable struct {
	coreFeaturesTable

	EXCLUDED coreFeaturesTable
}

// AS creates new CoreFeaturesTable with assigned alias
func (a CoreFeaturesTable) AS(alias string) *CoreFeaturesTable {
	return newCoreFeaturesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CoreFeaturesTable with assigned schema name
func (a CoreFeaturesTable) FromSchema(schemaName string) *CoreFeaturesTable {
	return newCoreFeaturesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CoreFeaturesTable with assigned table prefix
func (a CoreFeaturesTable) WithPrefix(prefix string) *CoreFeaturesTable {
	return newCoreFeaturesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CoreFeaturesTable with assigned table suffix
func (a CoreFeaturesTable) WithSuffix(suffix string) *CoreFeaturesTable {
	return newCoreFeaturesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCoreFeaturesTable(schemaName, tableName, alias string) *CoreFeaturesTable {
	return &CoreFeaturesTable{
		coreFeaturesTable: newCoreFeaturesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newCoreFeaturesTableImpl("", "excluded", ""),
	}
}

func newCoreFeaturesTableImpl(schemaName, tableName, alias string) coreFeaturesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		IconColumn      = postgres.StringColumn("icon")
		RequiredColumn  = postgres.BoolColumn("required")
		DataTypeColumn  = postgres.StringColumn("data_type")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, IconColumn, RequiredColumn, DataTypeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{IconColumn, RequiredColumn, DataTypeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return coreFeaturesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Icon:      IconColumn,
		Required:  RequiredColumn,
		DataType:  DataTypeColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
