//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CoreFeaturesI18n = newCoreFeaturesI18nTable("public", "core_features_i18n", "")

type coreFeaturesI18nTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	CoreFeatureID postgres.ColumnInteger
	Name          postgres.ColumnString
	Description   postgres.ColumnString
	LanguageCode  postgres.ColumnString
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CoreFeaturesI18nTable struct {
	coreFeaturesI18nTable

	EXCLUDED coreFeaturesI18nTable
}

// AS creates new CoreFeaturesI18nTable with assigned alias
func (a CoreFeaturesI18nTable) AS(alias string) *CoreFeaturesI18nTable {
	return newCoreFeaturesI18nTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CoreFeaturesI18nTable with assigned schema name
func (a CoreFeaturesI18nTable) FromSchema(schemaName string) *CoreFeaturesI18nTable {
	return newCoreFeaturesI18nTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CoreFeaturesI18nTable with assigned table prefix
func (a CoreFeaturesI18nTable) WithPrefix(prefix string) *CoreFeaturesI18nTable {
	return newCoreFeaturesI18nTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CoreFeaturesI18nTable with assigned table suffix
func (a CoreFeaturesI18nTable) WithSuffix(suffix string) *CoreFeaturesI18nTable {
	return newCoreFeaturesI18nTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCoreFeaturesI18nTable(schemaName, tableName, alias string) *CoreFeaturesI18nTable {
	return &CoreFeaturesI18nTable{
		coreFeaturesI18nTable: newCoreFeaturesI18nTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newCoreFeaturesI18nTableImpl("", "excluded", ""),
	}
}

func newCoreFeaturesI18nTableImpl(schemaName, tableName, alias string) coreFeaturesI18nTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		CoreFeatureIDColumn = postgres.IntegerColumn("core_feature_id")
		NameColumn          = postgres.StringColumn("name")
		DescriptionColumn   = postgres.StringColumn("description")
		LanguageCodeColumn  = postgres.StringColumn("language_code")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		allColumns          = postgres.ColumnList{IDColumn, CoreFeatureIDColumn, NameColumn, DescriptionColumn, LanguageCodeColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns      = postgres.ColumnList{CoreFeatureIDColumn, NameColumn, DescriptionColumn, LanguageCodeColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return coreFeaturesI18nTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		CoreFeatureID: CoreFeatureIDColumn,
		Name:          NameColumn,
		Description:   DescriptionColumn,
		LanguageCode:  LanguageCodeColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
