//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Agencies = Agencies.FromSchema(schema)
	AgenciesI18n = AgenciesI18n.FromSchema(schema)
	CoreFeatures = CoreFeatures.FromSchema(schema)
	CoreFeaturesI18n = CoreFeaturesI18n.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Uploads = Uploads.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
