//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Users = newUsersTable("public", "users", "")

type usersTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	EmailAddress   postgres.ColumnString
	PasswordHash   postgres.ColumnString
	PhoneNumber    postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp
	LastLoginAt    postgres.ColumnTimestamp
	Name           postgres.ColumnString
	IsActive       postgres.ColumnBool
	ProfilePicture postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		EmailAddressColumn   = postgres.StringColumn("email_address")
		PasswordHashColumn   = postgres.StringColumn("password_hash")
		PhoneNumberColumn    = postgres.StringColumn("phone_number")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		LastLoginAtColumn    = postgres.TimestampColumn("last_login_at")
		NameColumn           = postgres.StringColumn("name")
		IsActiveColumn       = postgres.BoolColumn("is_active")
		ProfilePictureColumn = postgres.StringColumn("profile_picture")
		allColumns           = postgres.ColumnList{IDColumn, EmailAddressColumn, PasswordHashColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn, LastLoginAtColumn, NameColumn, IsActiveColumn, ProfilePictureColumn}
		mutableColumns       = postgres.ColumnList{EmailAddressColumn, PasswordHashColumn, PhoneNumberColumn, CreatedAtColumn, UpdatedAtColumn, LastLoginAtColumn, NameColumn, IsActiveColumn, ProfilePictureColumn}
	)

	return usersTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		EmailAddress:   EmailAddressColumn,
		PasswordHash:   PasswordHashColumn,
		PhoneNumber:    PhoneNumberColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,
		LastLoginAt:    LastLoginAtColumn,
		Name:           NameColumn,
		IsActive:       IsActiveColumn,
		ProfilePicture: ProfilePictureColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
