// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package agencies

import (
	"database/sql"
)

// Injectors from wire.go:

func Initialize(database *sql.DB) *handler {
	agenciesRepo := NewRepo(database)
	agenciesService := NewService(agenciesRepo)
	agenciesHandler := NewHandler(agenciesService)
	return agenciesHandler
}
