import Footer from "@/components/customer/shared/footer";
import HeaderNavigationBar from "@/components/customer/shared/header-navigation-bar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderNavigationBar />
        <div className="mx-auto max-w-supported">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
