// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package uploads

import (
	"database/sql"
)

// Injectors from wire.go:

func Init(datbase *sql.DB) *handler {
	uploadsRepo := NewRepo(datbase)
	uploadsService := NewService(uploadsRepo)
	uploadsHandler := NewHandler(uploadsService)
	return uploadsHandler
}
