// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"database/sql"
)

// Injectors from wire.go:

func Init(database *sql.DB) *handler {
	authRepo := NewRepo(database)
	authService := NewService(authRepo)
	authHandler := NewHandler(authService)
	return authHandler
}
