// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package listings

import (
	"database/sql"
)

// Injectors from wire.go:

func Init(databse *sql.DB) *handler {
	listingsRepo := NewRepo(databse)
	listingsService := NewService(listingsRepo)
	listingsHandler := NewHandler(listingsService)
	return listingsHandler
}
