import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { BasePageParams } from "@/lib/types/types";
import { NextIntlClientProvider, useMessages } from "next-intl";
import HeaderNavigationBar from "@/components/shared/header-navigation-bar";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: BasePageParams) {
  const messages = useMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    // TODO: add `dir` to `<html>` when supporting an rtl language
    <html lang={locale} dir={dir}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body className={inter.className}>
          <HeaderNavigationBar />
          <div className="max-w-supported mx-auto">{children}</div>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
