import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { BasePageParams } from "@/lib/types/types";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: BasePageParams) {
  const messages = useMessages(); 

  return (
    // TODO: add `dir` to `<html>` when supporting an rtl language
    <html lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body className={inter.className}>{children}</body>
      </NextIntlClientProvider>
    </html>
  );
}
